name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release

      - name: Create release archive
        run: |
          mkdir -p artifacts
          cp target/release/crate-report artifacts/
          tar -czf artifacts/crate-report-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz -C artifacts crate-report

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            artifacts/crate-report-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
