name: Safety Analysis

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  safety-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build crate-report
      run: cargo build --release

    - name: Generate baseline from main branch
      run: |
        # Switch to main branch to generate baseline
        git fetch origin main
        git checkout origin/main

        # Generate baseline report
        ./target/release/crate-report --format csv --output baseline.csv

        # Switch back to PR branch
        git checkout ${{ github.sha }}

    - name: Generate PR safety report
      run: |
        # Generate PR report with baseline comparison
        ./target/release/crate-report --baseline baseline.csv --format pr-comment --output pr-comment.md

    - name: Comment on PR
      if: success()
      run: |
        # Check if comment file exists and has content
        if [ -f pr-comment.md ] && [ -s pr-comment.md ]; then
          # Look for existing bot comment
          COMMENT_ID=$(gh pr view ${{ github.event.number }} --json comments --jq '.comments[] | select(.author.login == "github-actions[bot]" and (.body | contains("Safety Analysis"))) | .id' | head -1)

          if [ -n "$COMMENT_ID" ]; then
            echo "Updating existing comment $COMMENT_ID"
            gh api repos/${{ github.repository }}/issues/comments/$COMMENT_ID \
              --method PATCH \
              --field body=@pr-comment.md
          else
            echo "Creating new comment"
            gh pr comment ${{ github.event.number }} --body-file pr-comment.md
          fi
        else
          echo "No significant safety changes detected, skipping comment"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload reports as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: safety-reports
        path: |
          baseline.csv
          pr-comment.md
        retention-days: 30
